### ISSUE TITLE
Make it possible to plot from the glob object (run_from_cli branch)

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/CarboCATLite#2]
It is currently prohbitively slow to run the model. To speed up the runs, we want to skip automatic plotting and make it possible to plot just the chronostratigraphic diagram (without other elements of the figure) post hoc from a saved `glob` object.

**Comment by NiklasHohmann** [comment]
Possible via function plotFinalGraphics_from_glob.m
