### ISSUE TITLE
Make a version with hard-coded parameters to run from shell? (needed for "the triangle")

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/CarboCATLite#9]
Currently CarboCATLite can be launched from the terminal like this:
```
matlab -nodesktop -nosplash -r "CarboCAT_cli("params/DbPlatform/paramsInputValues.txt", "params/DbPlatform/paramsProcesses.txt", "model_run_42", "params/DbPlatform/seaLevelConst3000iterations.txt", false); exit"
```
It starts correctly but gives the following matlab error:
`Unrecognized function or variable 'params'.`
The same command run from inside matlab works fine.

Starting matlab from shell according to https://stackoverflow.com/questions/33187141/how-to-call-matlab-script-from-command-line

What is the solution to this? Substitute the files in their location for each run and hardcode a path so it doesn't have to be passed as a parameter?

**Comment by EmiliaJarochowska** [comment]
I found this solution but it seems overly complicated:
https://stackoverflow.com/questions/12306333/matlab-command-from-bash-command-line-on-an-already-running-session

**Comment by chStaiger** [comment]
You are using the double quotes twice, once to wrap the command and once to indicate the folder name. So matlab thinks `params` is a command. Can you try single quotes around your paths?

**Comment by EmiliaJarochowska** [comment]
You are right! It worked now. Thank you very much 🙏🏻
